development:
  adapter: jdbcmysql
  encoding: utf8
  database: jtasks
  username: root
  password:
      
production:
  adapter: jdbcmysql
  encoding: utf8
  database: jtasks
  username: root
  password:      
